# Generated by Django 3.2.8 on 2023-07-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('reading', models.DecimalField(max_digits=10, decimal_places=2)),
                ('stamp', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
