# Generated by Django 3.2.8 on 2023-07-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='new_field',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
